# Generated by Django 4.1.7 on 2023-05-03 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999)]),
        ),
    ]
